name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - working-directory: ./streamlit_text_label/frontend
        run: npm install
      - working-directory: ./streamlit_text_label/frontend
        run: npm run build
